### ISSUE TITLE
contact form produced in test, not in prod (public dir)

### ISSUE THREAD

**Issue by comstock** [appernetic/hugo-nederburg-theme#12]
Hugo is generating a working contact form in test, e.g.: `hugo server` and `hugo server -D`.

When I run `hugo` and generate a contact form in `public` and depoly, the get a contact page without the form text.

Any suggestions appreciated.

**Comment by jalexandre0** [comment]
@comstock, 

What is your hugo version for test and production? For some reason, contact is built nicely  on 0.34 and have the issue you described on 0.39 (the only versions I tested).

I changed both test and prod env to 0.34. :)

**Comment by comstock** [comment]
Thanks for the reply. i'm using hugo on multiple machines, all installations recent. 

v0.38.2 darwin/amd64

**Comment by appernetic** [comment]
Hi,
I will test it with 0.40, have a very high workload at the moment but will try to shoehorn it in over the weekend.

**Comment by appernetic** [comment]
Hi!
I think that I just have fixed the issue. It was just to rename the the file in content/contact/ from index.html to _index.html and /layout/contat/single.html to list.html

The changes is in the exampleSite folder.

@jalexandre0 You should add the pt-br translation in a separate i18n file and add placeholders for it in the contact file.
