### ISSUE TITLE
tags and categories don't work for me

### ISSUE THREAD

**Issue by norayr** [appernetic/hugo-nederburg-theme#13]
hello,

you can see the source at https://github.com/norayr/film-magazine/
and the live version at http://ժապաւէն.հայ/

i am sure in spite of the unknown characters you'll be able to recognize where are categories and tags shown.

so, i have added categories and tags in every post, but i can see two problems:

* post pages show all the tags and all the categories, not the tags specific to the post.
* clicks on category or tag pages brings an empty page: http://ժապաւէն.հայ/categories/%d5%b5%d6%85%d5%a4%d5%b8%d6%82%d5%a1%d5%ae%d5%b6%d5%a5%d6%80/

i don't have much experience with web and this is my first work with hugo so may be this is not theme related and i don't understand something.

can you advice what can i try, or what is what i am obviously doing wrong?

**Comment by appernetic** [comment]
Hi norayr,
interesting site by the way! Have you tried first with the exampleSite? That way you can start and build on something that is working. You also get a feel for the structure and how to add new content, categories and tags.

I am a bit overworked right now. But I keep an eye on this and feel free to ask anything.

Regards,

Göran

**Comment by norayr** [comment]
hey hey. thank you for solving the issue when all the tags are displayed instead of only necessary ones.

however, the second issue (click on category or tag brings an empty page) remains unresolved. as i have commented in #14

>i also tried the other theme, and both tags and categories work with or without the quotes.
>so i guess the second issue also is indeed theme related.

shell i open a separate issue regarding that?

**Comment by appernetic** [comment]
Hi, yes please open a separate issue. It will be easy to miss..
