### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by MayaGans** [appernetic/hugo-nederburg-theme#15]
I firstly just wanted to mention how I'm really enjoying this theme! I'm new to CSS and it seems images don't scale to the size of blog post blocks (this occurs upon mobile viewing as well). I was wondering where and what to write within the code to make images responsive? Thank you!

**Comment by appernetic** [comment]
Hi MayaGans,
I'm glad you enjoy the theme! 
This theme is based on the WP tracks theme and the css is custom built and does not use any css framework, so there is no simple way to add responsive images. There is a sccs file in the orginal wp theme you can start with if needed, to make it work. Maybe the WP theme creator have updated the css to include responsive images. I can imagine that it is a lot of code to add for different screen resolutions. I have not checked out how they did it in Bootstrap or Bulma. But I guess that  it could take anything from 8 to 16 hours. 

Start by checking the css file:  hugo-nederburg-theme/static/css/style.css there you have links to the original theme and the scss it's built from.

Good luck!

**Comment by appernetic** [comment]
I have also just tested the theme https://themes.gohugo.io/theme/hugo-nederburg-theme/post/work2/ in al kinds of devices from Apple ipad, iphone 4 - 6, samsung galaxy 3 - 7, google nexus 4 - 7 and desktop browsers and every image seems very responsive.
