### ISSUE TITLE
Add a "RSS Feed" button in social links

### ISSUE THREAD

**Issue by Argann** [appernetic/hugo-nederburg-theme#18]
Hello ! First of all, thank you for this awesome theme :wink: 

Well, it's not a bug, but just an ask for a new feature, so I don't know if it's _the right place_ to ask ?

It would be awesome to add a button to subscribe to the RSS feed of the current site in the social icons !
I'm new tu hugo, but i think it's quite easy, since hugo itself generates the required XML files.

**Comment by appernetic** [comment]
Hi, great that you like the theme.

You can ask for features here. Feel free to develop this feature and  then post a PR!
