### ISSUE TITLE
Hugo tip

### ISSUE THREAD

**Issue by bep** [appernetic/hugo-nederburg-theme#2]
https://github.com/appernetic/hugo-nederburg-theme/blob/b82515669d7d28cab0dd96ba194f767413f5f9e6/layouts/partials/portfolio.html#L4

Tip: `.Site.RegularPages` will be the same as checking for `IsPage`.

**Comment by appernetic** [comment]
Ok, thanks!
I was happy to make it work at all. 

So I should replace: 

{{ $paginator := .Paginate (where (where .Site.Pages "Type" "post") "IsPage" true) }} 

with this:

{{ $paginator := .Paginate (where (where .Site.Pages "Type" "post") .Site.RegularPages) }}

**Comment by bep** [comment]
>{{ $paginator := .Paginate (where (where .Site.Pages "Type" "post") .Site.RegularPages) }}

No.

```
{{ $paginator := .Paginate (where .Site.RegularPages "Type" "post") }}
```

Even better would be:

https://github.com/bep/editorial/blob/master/layouts/index.html#L2

Note that the magic `.Site.Params.mainSections` will always have a value in a Hugo site (defaults to the section with most pages).

**Comment by appernetic** [comment]
Ok! Thanks for the clarification!
