### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by pilgrimagehome** [appernetic/hugo-nederburg-theme#20]
Hello! 
Sorry I'm relatively new to git and hugo. 
I'm having trouble reproducing the contact page on my site. I made a _index.md file under content/contact. But it doesn't seem to be reproducing the formspree form. Even when I plug in the basic form it generates without formatting. Any idea as to what I might be doing wrong?

**Comment by appernetic** [comment]
Maybe you don't have the email configured in the config.toml file?
