### ISSUE TITLE
Customizing tags/categories

### ISSUE THREAD

**Issue by ghost** [appernetic/hugo-nederburg-theme#22]
Hi,

is there any way how to change the tags/categories? Adding new one or deleting existing one?

Thanks

**Comment by appernetic** [comment]
You add tags and categories in the markdown files. First make sure you have taxonomies in your config file (it should be there if you use the exampleSite config file):

[taxonomies]
   tag = "tags"
   category = "categories"

Then in the yaml front matter:

title: My article
categories: [hugo, blog]
tags: [hugo,content,static site generator]
