### ISSUE TITLE
Images do not scale

### ISSUE THREAD

**Issue by farokhj** [appernetic/hugo-nederburg-theme#24]
Thank you for porting Tracks to Hugo.  I started using your theme and quickly discovered that images in my blog posts do not scale with resizing of the browser window.  I fixed this easily by creating my own `static/css/style.css` that contains:

`img {
  max-width: 100%;
  height: auto;
  line-height: 0;
}`

However, proper image display and scaling should be a default feature of the theme that doesn't require this sort of modification by the user.

**Comment by appernetic** [comment]
Hi, yes I agree. Good that you found a solution.
