### ISSUE TITLE
Support for multiple writers

### ISSUE THREAD

**Issue by lherman-cs** [appernetic/hugo-nederburg-theme#26]
Recently, I just integrated this theme to my hugo server. However, I found that this theme was lacking in multiple writers support. So, is there any work around this? Or is this something that won't be implemented?

Thanks

**Comment by appernetic** [comment]
Hi, I don't think it's going to be implemented unless someone does a PR.

**Comment by lherman-cs** [comment]
Hi @appernetic, I just made a PR for this: https://github.com/appernetic/hugo-nederburg-theme/pull/29.
