### ISSUE TITLE
inLanguage parameter stuck in pt-BR

### ISSUE THREAD

**Issue by farokhj** [appernetic/hugo-nederburg-theme#27]
Hi there,
My posts all have inLanguage set to pt-BR even though I'm writing in English.  Specifically, the HTML of any page on the site lists this:

script type="application/ld+json">  
    {  
        "@context" : "http://schema.org",  
        "@type" : "BlogPosting",  
  ...  
        "description" : "",  
        "inLanguage" : "pt-BR",  
  ...  
}

Any way to fix this?  Thank you.

**Comment by appernetic** [comment]
Hi, sorry for the problem, it was hard coded in  hugo-nederburg-theme/layouts/partials/schema.html
, I have now changed it to en.
