### ISSUE TITLE
Theme won't start

### ISSUE THREAD

**Issue by paskal** [appernetic/hugo-nederburg-theme#3]
Hello!

My [blog](https://github.com/paskal/terrty/tree/master/blog) won't start with your theme:
```
➜  blog git:(master) ✗  docker-compose run --service-ports blog-preview
Building sites … ERROR 2018/03/20 09:45:43 Error while rendering "page" in "post/": template: /srv/hugo/themes/hugo-nederburg-theme/layouts/_default/single.html:86:51: executing "main" at <absURL>: wrong number of args for absURL: want 1 got 0
ERROR 2018/03/20 09:45:43 Error while rendering "page" in "": template: /srv/hugo/themes/hugo-nederburg-theme/layouts/_default/single.html:86:51: executing "main" at <absURL>: wrong number of args for absURL: want 1 got 0
ERROR 2018/03/20 09:45:43 Error while rendering "home" in "": template: /srv/hugo/themes/hugo-nederburg-theme/layouts/index.html:3:9: executing "/srv/hugo/themes/hugo-nederburg-theme/layouts/index.html" at <partial "head.html" ...>: error calling partial: template: theme/partials/head.html:3:76: executing "theme/partials/head.html" at <safeHTML>: wrong number of args for safeHTML: want 1 got 0
```
I've tried to move all "content" to "post" subfolder, no luck. I guess input handling could be improved to provide clearer error messages than "wrong number of args for safeHTML".

Thanks for the effort!

**Comment by appernetic** [comment]
Hi,
it's Hugo built in error messages so we have to stick with them. 

Did you use the settings in the config.toml from the exampleSite folder?

Also use at least Hugo version 0.34. 

There should be no problem if you configure it right as you can see here: 

https://themes.gohugo.io/theme/hugo-nederburg-theme/

**Comment by paskal** [comment]
The thing I'm trying to achieve is to be able to look at the theme without adjusting my configuration.

My Hugo version is 0.37, you could find a good example on what could be done here for making life easier for someone migrating existing site to your theme by link: https://github.com/yursan9/manis-hugo-theme/issues/4

**Comment by appernetic** [comment]
I don't have time to look at it at the moment. But you can always do a PR.

**Comment by appernetic** [comment]
Be my first [Patreon](https://www.patreon.com/appernetic) and I start with it ASAP!

**Comment by paskal** [comment]
I'm waiting:)

**Comment by appernetic** [comment]
Check it out and see if it works as you would prefer it!

**Comment by paskal** [comment]
It works and it's nice! Two things:

1. Author block could be hidden in case there are no variables set
![image](https://user-images.githubusercontent.com/712534/37853817-5db10dd6-2ef9-11e8-9938-48fb20f4d0f8.png)

2. I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37853843-720a234e-2ef9-11e8-9566-25c1bc22e267.png)

It breaks all the formatting. Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by appernetic** [comment]
Thanks,  I fix this issues tomorrow!



Den fre 23 mars 2018 22:23Dmitry Verkhoturov <notifications@github.com>
skrev:

**Comment by appernetic** [comment]
I added check for author before the author-meta now: https://github.com/appernetic/hugo-nederburg-theme/blob/920700a5a728db8d6ab0b368c775404b64e4ddeb/layouts/_default/single.html#L80
