### ISSUE TITLE
Broken Disqus Style

### ISSUE THREAD

**Issue by lherman-cs** [appernetic/hugo-nederburg-theme#30]
I just recently installed disqus to my blog. But, apparently, the style is broken. Following is the screenshot:

![broken_disqus](https://user-images.githubusercontent.com/15654932/43359187-61389f2e-926c-11e8-93bf-2109b0c584e1.png)

I noticed that the style came from Hugo's internal partial. I've been trying to fix this. But, I still couldn't find a solution yet. Any help would be helpful. Thanks!

**Comment by justinellison** [comment]
Just ran across this as well.  Changing the padding of 285px [here](https://github.com/appernetic/hugo-nederburg-theme/blob/master/static/css/custom.css#L2660) to 0px makes it better.  It has something to do with the responsive CSS, if you make your browser window thinner, the problem gets better.  Someone with more experience with responsive design and CSS than me will have to fix this one, I'm out of my league :)

**Comment by justinellison** [comment]
It turns out just removing the custom styling for disqus at different resolutions fixes the problem, and is still responsive.  PR created.

**Comment by justinellison** [comment]
That PR will break the post's main image, I've closed the PR.  If someone better at CSS than I am could lend a hand, I'd appreciate it.

**Comment by justintime** [comment]
Sorry for the mess.  When I created the PR, I pulled down the latest master, and I got bitten by the move of the image in #25.  So, the fix worked, and it didn't have any regressions.  I've created a new PR that should be good to go.  I have this fix deployed and running on my blog if you want to verify it: https://bluewantingred.com/post/ad-password-audit-in-kali/

**Comment by lherman-cs** [comment]
That looks good to me!

**Comment by appernetic** [comment]
Ok, great! I will commit the PR!
