### ISSUE TITLE
homepage head title adds space and dash

### ISSUE THREAD

**Issue by Korka13** [appernetic/hugo-nederburg-theme#37]
This template is beautiful!
in the head title is added a dash and a space.
In Layouts>partials>head.html I modified line 5 to:
{{ with .Title }} <title>{{- . -}} {{if $.IsHome}}{{ $.Site.Params.slogan | default "" | safeHTML }}{{ end }}</title>
to solve the problem
Thanks!

**Comment by appernetic** [comment]
I think the intention is to have a title and slogan on every page title. Like this:

Home - My blog
Another page - My blog
