### ISSUE TITLE
home bottom on header pointing to wrong address

### ISSUE THREAD

**Issue by cbenitez81** [appernetic/hugo-nederburg-theme#4]
When creating a website in a folder different than the root, for example www.somepage.com/blog/, the home bottom on the header always poinst to www.somepage.com, instead of the main page of blog.  I notice this in the header of the partial

```
<div id='site-title' class='site-title'>
    {{ with .Site.Title }}
    <a href="/"> {{ . }} </a>
    {{ end }}</div>
 </div>
```
It seems that the third line above always poinst to the root site.  I think that a better behavior would change that line to
```<a href="./"> {{ . }} </a>``` , meaning changing "/" to "./"

Similar trick can be applied in line 20 and 26 of the header.html.

I used hugo version 0.37 on windows 7.

thanks!

**Comment by appernetic** [comment]
Or maybe use absURL instead?

Den fre 30 mars 2018 14:52cbenitez81 <notifications@github.com> skrev:

**Comment by cbenitez81** [comment]
That is a possibility or the other one is to attach the baseurl that we use in config.toml

**Comment by appernetic** [comment]
I have added .SiteBaseURL to line: https://github.com/appernetic/hugo-nederburg-theme/blob/920700a5a728db8d6ab0b368c775404b64e4ddeb/layouts/partials/header.html#L4
