### ISSUE TITLE
Category links fail when you have a two word category 

### ISSUE THREAD

**Issue by MatthewMcD** [appernetic/hugo-nederburg-theme#42]
In three places the link for a two word category (like ["pet photo"]) fails because the URL is not `urlize`'d. I have this fixed and need to submit a PR. Posting this for tracking purposes.

**Comment by appernetic** [comment]
Ok, great!

**Comment by MatthewMcD** [comment]
OK, by "later today"' I really meant "later..." hopefully this week.
