### ISSUE TITLE
Home Page Post Order

### ISSUE THREAD

**Issue by MatthewMcD** [appernetic/hugo-nederburg-theme#44]
It might be "just me" but I am seeing that the posts on the home page do not sort in date order.

I am at a loss for how to change the sort order to fix it. Ideally we could add a token to the config file.

**Comment by andretti1977** [comment]
I see the posts correctly ordered by date descending. See my customization:
[devamountain.com](https://www.devamountain.com/)

**Comment by MatthewMcD** [comment]
Did you make any changes? Your repo says it's up to date with appernetic:master. If you did can you push the branch?

**Comment by andretti1977** [comment]
My site repo is not the one you see forked on github account. I did customizations to the theme, but didn't change anything related to page ordering so it should work for you too.

**Comment by MatthewMcD** [comment]
So...it's me. :) I'll have a look.

**Comment by MatthewMcD** [comment]
I just retested with a fresh clone and used the sample site (which we should update the sample posts to have different dates). It lists them in "file order".

**Comment by MatthewMcD** [comment]
@andretti1977  can you check your `portfolio.html` page? I found that adding `.ByDate.Reverse` to the range paginator solved the problem. The question is: Should this be the default behavior or should it be optional and configured in the `config.toml` file? @appernetic Thoughts?

I'll submit a PR that includes this and updates to the work files so that they have different dates and categories and tags.

**Comment by andretti1977** [comment]
That's strange: i've just tried on my local istance changing the date of the second post and it is shown in the correct order (see the picture below where welcome post is the most recent one and compare it with the online istance where welcome post is the oldest).
Just consider i have this format date in front matter section: `date = "Thu Aug 25 10:00:00 CEST 2018"`

![image](https://user-images.githubusercontent.com/856429/46082023-49af0300-c19e-11e8-8b7d-120af8630f27.png)

**Comment by MatthewMcD** [comment]
Have you tried it with the sample site and the sample content work#.md files? That was my test. The date format is date = `"2015-04-11T18:25:22+05:30"`

**Comment by andretti1977** [comment]
It may be an issue with date format? Can you try setting date in the same format i suggested to you and verify if it works?

**Comment by MatthewMcD** [comment]
What date format is that? I am using [this date converter](http://www.coryking.com/date-converter.php) to go from the W3C format in the samples.

**Comment by andretti1977** [comment]
I must be honest with you, i can't find the source of that format! I found it on some hugo post examples online but can't address the source anymore.
Have you tried with that format? Does it work for you?

**Comment by MatthewMcD** [comment]
I can't explain it, but it does not work for me using the following dates in order from `work1-11`:
date = "Sat Apr 11 12:55:00 CEST 2015"
date = "Sat Nov 05 09:11:00 CEST 2016"
date = "Wed Sep 05 09:14:00 CEST 2018"
date = "Sat Nov 05 09:09:00 CEST 2016"
date = "Sat Nov 05 08:15:00 CEST 2016"
date = "Sun Oct 08 09:24:00 CEST 2017"
date = "Sat Nov 05 09:29:00 CEST 2016"
date = "Fri May 16 09:00:00 CEST 2014"
date = "Sat Feb 14 08:52:00 CEST 2015"
date = "Sat Oct 7 01:00:00 CEST 2017"

I get the following result (I added the year to the slug for clarity).
![image](https://user-images.githubusercontent.com/7558738/46086492-d2617b00-c16d-11e8-84f8-51a96ccec3cb.png)

Adding `.ByDate.Reverse` to `portfolio.html` forces the correct order.
![image](https://user-images.githubusercontent.com/7558738/46086668-32582180-c16e-11e8-91af-4729a06de583.png)

Hugo should be converting the `date` string in the front matter to a date before sorting. So the format should have no bearing on the order.
  
Edit: I even screwed up and used a different format for one of the dates and the sort order works fine now.

**Comment by andretti1977** [comment]
Sorry but i don't know what to say...i just added to local server a new post and played with date and it worked correctly.
This is a sample front matter (added a custom param):
```
+++
showonlyimage = true
draft = false
image = "img/mika-luoma-660672-unsplash.jpg"
date = "Thu Sep 25 10:00:00 CEST 2018"
title = "Create and host a static site for free"
categories = [ "entrepreneurship"]
tags = ["business development", "developer"]
weight = 1
image_caption = "<a href='https://unsplash.com/photos/9pI8YM99hhY' target='_blank'>Photo by Mika Luoma on Unsplash</a>"
+++
```

**Comment by MatthewMcD** [comment]
What happens when you start from a fresh site and then clone the repo into your site? That is how I have been testing. (Rather than using your front matter.)

**Comment by appernetic** [comment]
Strange. But .ByDate.Reverse is a good fix, and I think that it should be a default behaviour, it's a blog.
