### ISSUE TITLE
Add logos in the footer of all pages

### ISSUE THREAD

**Issue by antonioggsousa** [appernetic/hugo-nederburg-theme#49]
Hi, 

I would like to add logos in the footer of each page, similar to what was done in the HUGO website (link: https://gohugo.io ). At the end of each page appear the logos of the sponsors. I would like to do something similar using the NEDERBURG theme. 

Can someone tell me how to do it. 
Thanks in advance!

**Comment by appernetic** [comment]
Check out the layouts folder, there you have all the templates. Then the best practice for customizing a theme is to copy the relevant files to your root layout folder with the same folder structure and file names. Then edit the files in the root/layouts folder. The changed files will then override the theme templates.

This way you can quickly customize your site without the risk of losing your changes if you need to update the theme.

**Comment by appernetic** [comment]
Closing!
