### ISSUE TITLE
horizontal lines when clicking on side bar 

### ISSUE THREAD

**Issue by rdiaz02** [appernetic/hugo-nederburg-theme#52]
If one resizes the browser window, so that the side bar is shown as three horizontal lines (the "fa-bars"), and then clicks on them, horizontal lines are displayed, and one gets this

![hlines](https://user-images.githubusercontent.com/1688611/51915172-ba7b5b80-23da-11e9-8093-02d00640dc6f.png)

How can this (the horizontal lines) be avoided? 

Edit: Since I think the problem is related to something that happens when clicking on the fa-bars, preventing the menu from turning into the fa-bars would be enough for me, but I do not see how to accomplish that either.

Edit 2: (I should have checked this before) The problem seems to be related to **specific browsers**. I cannot reproduce it under Linux with google chrome, Konqueror, uzbl, or qutebrowser, and I only observe it with Firefox (65.0) on one computer (but not with an older FF on another machine).  On an Android phone I do not see it with Firefox or Chrome, though the transition is very slow on Firefox.

Regardless, I'd love to be able to disable the turning into the fa-bars, and keep the sidebar entries always present.

**Comment by appernetic** [comment]
What happens if you reload the page after resizing?

**Comment by appernetic** [comment]
I have pushed the latest font awesome icons also. So check with the newest version also.

**Comment by rdiaz02** [comment]
Thanks. I've pulled the latest changes. If I reload the page, everything is OK (i.e., horizontal lines disappear).

**Comment by appernetic** [comment]
Great to her!
