### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by brodieG** [appernetic/hugo-nederburg-theme#53]
First, thanks for porting the theme to Hugo.  It's a great theme and I'm looking forward to using and adapting.

In poking around though, I noticed that the original theme this is ported from is licensed under GPL-2.  From [terms and conditions](https://www.competethemes.com/terms-of-use/), bullet 2:

> Our WordPress themes and plugins are released under the GNU Public License version 2.0. 

This is supported by the copyright notices in [the source files](https://github.com/appernetic/hugo-nederburg-theme/blob/master/static/css/style.css#L12).

I am no lawyer, so it is possible that under this particular structure this is permissible, although it is not obvious to me that it would be, particularly since you're redistributing at a minimum the CSS file, and probably more implicitly in the HTML structure in the partials, etc.

Obvious options are:

1. Confirming the GPL-2 restrictions don't apply in this case.
2. Re-license this as GPL-2, assuming no other license conflicts
3. Ask Tracks to re-license at least the version you are using to be MIT compatible, which GPL-2 is not

I understand the appeal of MIT for a broadest possible audience, but I would encourage you to consider GPL licenses even if it turns out to be unnecessary in this current circumstance to ensure that others benefiting from your work are required to in turn share theirs with everyone else.

To be clear, I do NOT represent Tracks in anyway, and I'm NOT making any takedown threats or anything like that.  I'm just pointing out what seems to me a licensing incompatibility.

**Comment by appernetic** [comment]
Your point 2 seems to be a no brainer or not.. Running low on battery and brain at the moment :-)

**Comment by brodieG** [comment]
Hopefully battery and brain have recharged.  If you're up for 2 then please do.  If you'd like I will submit a PR that does it.

**Comment by appernetic** [comment]
Hi, sorry for my abcense. Yes please submit a PR.

**Comment by balibebas** [comment]
https://www.gnu.org/licenses/license-list.en.html#Expat

**Comment by ghost** [comment]
https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html#mit-and-bsd-attribution-is-a-land-mine fyi

**Comment by goransv** [comment]
Damn a land mine! 💣💣, ah mit and bsd ok! Thanks for the link!
