### ISSUE TITLE
Allow customization of copyright in theme config

### ISSUE THREAD

**Issue by pmviva** [appernetic/hugo-nederburg-theme#6]
I would like to add customization of copyright message in the theme configuration, maybe an array of strings, one for each paragraph in the footer, having the actual copyright as a default value.

**Comment by appernetic** [comment]
Hi, yes an array of strings would be good. Make it HTML safe also.

**Comment by pmviva** [comment]
I was thinking applying markdownify for each entry in the array. So you can configure each copyright entry using markdown directly as any other content in the site.
