### ISSUE TITLE
function "newScratch" not defined

### ISSUE THREAD

**Issue by georgeben** [appernetic/hugo-nederburg-theme#62]
The hugo website runs perfectly locally, but when I try to deploy to netlify, I get the error:

`Failed to add template "_default/single.html" in path "_default/single.html": template: _default/single.html:8: function "newScratch" not defined`

Please what can I do?

**Comment by MatthewMcD** [comment]
Are you running the same Hugo version in both places?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by georgeben** [comment]
@MatthewMcD I just changed the version of hugo on Netlify to the latest version. Everything works smoothly now. Thank you very much.

**Comment by MatthewMcD** [comment]
Excellent, that is a common issue when changing from local development. The other is metting with the root url.

M

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
